spring:
  application:
    name: blogPlatform
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: blogPlatform
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: blog-platform
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


cloudinary:
  cloud-name: ${cloudinary_cloud_name}
  api-key: ${cloudinary_api_key}
  api-secret: ${cloudinary_api_secret}

server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}
