spring:
  application:
    name: blogPlatform
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: blogPlatform
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}
